### PR TITLE
Added Korean Translation

### PR DESCRIPTION
**Pull request by gyular**
If you fine, please add korean translation

### CODE REVIEW

**Comment by Kira-NT** [comment]
Of course I'm fine with it! Thanks a lot for your contribution!

I want to add a few more things *(which will require translations too)* to the mod in the next few days, so I'll keep the PR opened until then. Hope, you are ok with it.

**Comment by Kira-NT** [comment]
```json
"key.packed-inventory.open_edit_screen": "Open edit screen",
```

changed to

```json
"key.packed-inventory.interact_with_item": "Interact with an item",
```

---

And there's a new line:

```json
"event.packed-inventory.failure.stack_consists_of_more_than_one_item": "It is not possible to edit more than one inventory at a time",
```
---

Please, update these translations in your file and it should be it :)

**Comment by gyular** [comment]
Updated new line and changed line

**Comment by Kira-NT** [comment]
Why... why did ya merge it back with 1.19? I switched to 1.18.x/dev for a reason :D

Anyway, thank you for your contributions!

**Comment by gyular** [comment]
sorry, i hardly inexperienced using git.
I see what you say about it.

**Comment by Kira-NT** [comment]
No worries! :D

**Pull request merged**
